Module VBModule
 
 Sub Main()

    Dim 01 as integer = Nothing
    Dim 02 as integer = Nothing
    Dim 03 as integer = Nothing
    Dim 04 as integer = Nothing
    Dim 05 as integer = Nothing
    Dim 06 as integer = Nothing
    Dim 07 as integer = Nothing
    Dim 08 as integer = Nothing
    Dim 09 as integer = Nothing
    Dim 10 as integer = Nothing
    Dim 11 as integer = Nothing
    Dim 12 as integer = Nothing
    Dim 13 as integer = Nothing
    Dim 14 as integer = Nothing
    Dim 15 as integer = Nothing
    Dim 16 as integer = Nothing
    Dim 17 as integer = Nothing
    Dim 18 as integer = Nothing
    
    Console.Write("What did you score on hole #1?")
    01 = Console.Readline()
    
    Console.Write("What did you score on hole #2?")
    02 = Console.Readline()
    
    Console.Write("What did you score on hole #3?")
    03 = Console.Readline()
    
    Console.Write("What did you score on hole #4?")
    04 = Console.Readline
    
    Console.Write("What did you score on hole #5?")
    05 = Console.Readline()
    
    Console.Write("What did you score on hole #6?")
    06 = Console.Readline()
    
    Console.Write("What did you score on hole #7?")
    07 = Console.Readline()
    
    Console.Write("What did you score on hole #8?")
    08 = Console.Readline()
    
    Console.Write("What did you score on hole #9?")
    09 = Console.Readline
    
    Console.Write("What did you score on hole #10?")
    10 = Console.Readline()
    
    Console.Write("What did you score on hole #11?")
    11 = Console.Readline()
    
    Console.Write("What did you score on hole #12?")
    12 = Console.Readline()
    
     Console.Write("What did you score on hole #13?")
    13 = Console.Readline()
    
    Console.Write("What did you score on hole #14?")
    14 = Console.Readline()
    
    Console.Write("What did you score on hole #15?")
    15 = Console.Readline()
    
    Console.Write("What did you score on hole #16?")
    16 = Console.Readline()
    
    Console.Write("What did you score on hole #17?")
    17 = Console.Readline()
    
    Console.Write("What did you score on hole #18?")
    18 = Console.Readline()
    
    Console.writeline ("Your Score Is: " & 01 + 02 + 03 + 04 + 05 + 06 + 07 + 08 + 09 + 10 + 11 + 12 + 13 + 14 + 15 + 16 + 17 + 18)
    
    End Sub 
End Module
